/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TebakWindow extends javax.swing.JFrame {
    int angkasoal;
    /**
     * Creates new form TebakWindow
     */
    public TebakWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mulaiButton = new javax.swing.JButton();
        petunjukLabel = new javax.swing.JLabel();
        inputAngkaTextField = new javax.swing.JTextField();
        cekAngkaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/fixGambar.png"))); // NOI18N
        jLabel1.setText("Tebak Angka");

        mulaiButton.setText("Mulai");
        mulaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiButtonActionPerformed(evt);
            }
        });

        petunjukLabel.setText("Klik Tombol Mulai");

        cekAngkaButton.setText("Cek Angka");
        cekAngkaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekAngkaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(inputAngkaTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(petunjukLabel)
                            .addComponent(mulaiButton)
                            .addComponent(cekAngkaButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mulaiButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(petunjukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAngkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cekAngkaButton)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiButtonActionPerformed
        // TODO add your handling code here:
        angkasoal = generateAngka();    //akan memanggil method private int generateAngka()
        petunjukLabel.setText("Masukkan angka - angka 1 - 100");
        mulaiButton.setEnabled(false);
    }//GEN-LAST:event_mulaiButtonActionPerformed

    private void cekAngkaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekAngkaButtonActionPerformed
        // TODO add your handling code here:
        try{
        String tebakan = inputAngkaTextField.getText();
        int tebak = Integer.parseInt(tebakan);
        if(tebak == angkasoal){
            petunjukLabel.setText("Pinter");
            inputAngkaTextField.setEnabled(false);
            mulaiButton.setEnabled(true);
        }else{
            String message;
            if(tebak < angkasoal){
                message = "Angka anda lebih kecil, Coba angka lebih besar";
            }else{
                message = "Angka anda lebih besar, Coba angka lebih kecil";
            }
            petunjukLabel.setText(message);
        }    
        }catch(Exception io){
            petunjukLabel.setText("Jangan dimasukan huruf IDIOT!!! ");
            Component rootpane = null;
            JOptionPane.showMessageDialog(rootpane, "Masukkan Angka! Ngerti angka ga?");
        }
        
        
    }//GEN-LAST:event_cekAngkaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private int generateAngka(){
        double random = Math.random()*100;
        double ceilValue = Math.ceil(random);
        int generateAngkaSoal = (int) ceilValue;
        return generateAngkaSoal;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekAngkaButton;
    private javax.swing.JTextField inputAngkaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mulaiButton;
    private javax.swing.JLabel petunjukLabel;
    // End of variables declaration//GEN-END:variables
}
